name: fzshell release

on:
  push:
    tags:
      - "*"

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    name: Release Go Binary
    build:
      needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.28
      with:
        goversion: 1.18
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "fzshell"
