name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
        go-version: [ "1.18" ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: lint
      uses: dominikh/staticcheck-action@v1.2.0
      with:
          version: "2022.1"
          install-go: false
          cache-key: ${{ matrix.go }}
    - name: vet
      run: "go vet ./..."
    - name: test
      run: |
        make test
